import TestRailNav from './TestRailNav'
import EvidenceActions, { EvidenceNames } from '../../components/EvidenceActions'
import useWorkspaceCollection from '../../hooks/useWorkspaceCollection'

const initialRows = Array.from({ length: 20 }, (_, index) => ({ req: `REQ-${String(101 + index).padStart(3, '0')}`, title: ['User can register with an email address', 'User can recover an account', 'Workspace owner can invite a teammate', 'Member can switch organizations', 'Planner can create a project', 'Developer can move issues across a board', 'Approver can record a decision', 'QA can add a test case', 'QA can record a test run result', 'Test cases link to delivery issues', 'Requirement coverage can be exported', 'User can upload a profile photo', 'Contact number is saved with country code', 'Notifications update when an event occurs', 'Admin can review audit history', 'Search returns workspace records', 'Mobile navigation stays usable', 'Test evidence remains private', 'Team members have role-based access', 'Workspace data stays separated'][index], source: `User story ${String(24 + index).padStart(3, '0')}`, tests: index % 7, coverage: ['100%', '100%', '100%', '75%', '50%', '0%'][index % 6], status: ['Covered', 'Covered', 'Covered', 'Partial', 'Partial', 'Missing'][index % 6], evidence: {} }))

function RTM() {
  const { data: rows, saveData: saveRows, loading, error } = useWorkspaceCollection('testrail-rtm', initialRows)
  function attach(id, kind, file) { if (file) saveRows(rows.map(row => row.req === id ? { ...row, evidence: { ...row.evidence, [kind]: file.name } } : row)) }
  function exportMatrix() {
    const escape = value => `"${String(value).replaceAll('"', '""')}"`
    const csv = [['Requirement', 'Title', 'Source', 'Tests', 'Coverage', 'Status'], ...rows.map(row => [row.req, row.title, row.source, row.tests, row.coverage, row.status])].map(line => line.map(escape).join(',')).join('\n')
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' }))
    const link = document.createElement('a'); link.href = url; link.download = 'elevate-requirements-traceability.csv'; link.click(); URL.revokeObjectURL(url)
  }
  const covered = rows.filter(row => row.status === 'Covered').length
  const coverage = rows.length ? Math.round(rows.reduce((total, row) => total + Number.parseInt(row.coverage, 10), 0) / rows.length) : 0
  return <main className="testrail-app"><TestRailNav active="RTM matrix" /><section className="testrail-main"><header className="testrail-topbar"><div>Elevate Workspace <b>/</b> RTM matrix</div><button className="jira-user">RH</button></header><div className="testrail-content"><div className="testrail-welcome"><div><p className="testrail-kicker">Coverage tracking</p><h1>Requirements traceability</h1><p>Connect requirements to test evidence and release confidence.</p></div><button className="testrail-primary" onClick={exportMatrix}>Export matrix ↓</button></div>{error && <p className="error-message" role="alert">Could not save traceability data: {error}</p>}<div className="rtm-summary"><div><strong>{coverage}%</strong><span>Overall coverage</span></div><div><strong>{rows.length}</strong><span>Total requirements</span></div><div><strong>{covered}</strong><span>Covered requirements</span></div><div><strong>{rows.length - covered}</strong><span>Need attention</span></div></div>{loading ? <p className="empty-state">Loading traceability matrix…</p> : <div className="rtm-table"><div className="rtm-head"><span>Requirement</span><span>Source</span><span>Tests</span><span>Coverage</span><span>Status</span><span>Evidence</span></div>{rows.map(row => <div className="rtm-row" key={row.req}><span><b>{row.req}</b><strong>{row.title}</strong><EvidenceNames evidence={row.evidence} /></span><span>{row.source}</span><span>{row.tests}</span><span><div className="mini-coverage"><i style={{ width: row.coverage }} /></div>{row.coverage}</span><span className={`case-status ${row.status.toLowerCase()}`}>{row.status}</span><EvidenceActions evidence={row.evidence} onAttach={(kind, file) => attach(row.req, kind, file)} /></div>)}</div>}</div></section></main>
}
export default RTM
