import { useState } from 'react'
import TestRailNav from './TestRailNav'
import { EvidenceNames } from '../../components/EvidenceActions'
import DeleteConfirm from '../../components/DeleteConfirm'
import CaseActionsMenu from '../../components/CaseActionsMenu'
import useWorkspaceCollection from '../../hooks/useWorkspaceCollection'

const caseTitles = ['A new user can register with valid details', 'An existing email receives a duplicate account message', 'A user can sign in with valid credentials', 'Invalid credentials show a safe error', 'A user can request a password reset', 'Expired reset links cannot change passwords', 'Password visibility toggle changes input type', 'Contact number saves with selected country code', 'Profile photo upload accepts supported image types', 'Profile photo upload rejects oversized files', 'Workspace owner can invite a teammate', 'Invitation can only be used once', 'Member cannot open another workspace record', 'Manager can approve a pending request', 'Completed approval cannot be decided twice', 'Jira issue appears in the correct board column', 'Test case links to a Jira issue', 'RTM export contains requirement coverage', 'Search filters matching workspace records', 'Mobile layout keeps primary actions visible']
const initialCases = caseTitles.map((title, index) => ({ id: `TC-${128 - index}`, title, suite: ['Accounts', 'Workspace', 'Delivery', 'Checkout', 'Reporting'][index % 5], priority: ['High', 'Normal', 'Low'][index % 3], status: ['Passed', 'Passed', 'Passed', 'Failed', 'Blocked', 'Not run'][index % 6], owner: ['RH', 'AK', 'SM', 'YK', 'JM'][index % 5], evidence: {} }))

function TestCases() {
  const { data: cases, saveData: saveCases, loading, error } = useWorkspaceCollection('testrail-cases', initialCases)
  const [query, setQuery] = useState('')
  const [modal, setModal] = useState(null)
  const [deleteId, setDeleteId] = useState(null)
  const [draft, setDraft] = useState({ title: '', suite: 'New suite', priority: 'Normal', status: 'Not run' })
  const visible = cases.filter((item) => `${item.id} ${item.title} ${item.suite}`.toLowerCase().includes(query.toLowerCase()))

  function openCreate() { setDraft({ title: '', suite: 'New suite', priority: 'Normal', status: 'Not run' }); setModal({ type: 'create' }) }
  function openEdit(item) { setDraft(item); setModal({ type: 'edit', id: item.id }) }
  function saveCase(event) { event.preventDefault(); if (!draft.title.trim()) return; if (modal.type === 'create') saveCases([{ ...draft, id: `TC-${130 + cases.length}`, owner: 'RH', evidence: {} }, ...cases]); else saveCases(cases.map((item) => item.id === modal.id ? { ...item, ...draft } : item)); setModal(null) }
  function removeCase(id) { setDeleteId(id) }
  function confirmDelete() { saveCases(cases.filter((item) => item.id !== deleteId)); setDeleteId(null) }
  function attach(id, kind, file) { if (file) saveCases(cases.map((item) => item.id === id ? { ...item, evidence: { ...item.evidence, [kind]: file.name } } : item)) }

  return <main className="testrail-app"><TestRailNav active="Test cases" /><section className="testrail-main"><header className="testrail-topbar"><div>Elevate Workspace <b>/</b> Test cases</div><div className="testrail-actions"><label>⌕ <input placeholder="Search" /></label><button className="jira-user">RH</button></div></header><div className="testrail-content"><div className="testrail-welcome"><div><p className="testrail-kicker">Test repository</p><h1>Test cases</h1><p>Create, update and validate every quality check.</p></div><button className="testrail-primary" onClick={openCreate}>＋ New test case</button></div>{error && <p className="error-message" role="alert">Could not save test case data: {error}</p>}<div className="case-toolbar"><div className="case-tabs"><button className="active">All cases <b>{cases.length}</b></button><button>My cases</button><button>Recently updated</button></div><label className="case-search">⌕ <input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search cases" /></label><button>☷ Filter</button></div>{loading ? <p className="empty-state">Loading test cases…</p> : <div className="case-table"><div className="case-table-head"><span>Case</span><span>Suite</span><span>Priority</span><span>Status</span><span>Owner</span><span>Actions</span></div>{visible.map((item) => <CaseRow key={item.id} item={item} onEdit={openEdit} onDelete={removeCase} onAttach={attach} />)}{!visible.length && <p className="empty-state">No test cases match this search.</p>}</div>}{modal && <CaseModal modal={modal} draft={draft} setDraft={setDraft} onSave={saveCase} onClose={() => setModal(null)} />}{deleteId && <DeleteConfirm label="test case" onCancel={() => setDeleteId(null)} onConfirm={confirmDelete} />}</div></section></main>
}

function CaseRow({ item, onEdit, onDelete, onAttach }) { return <div className="case-row"><span><b>{item.id}</b><strong>{item.title}</strong><EvidenceNames evidence={item.evidence} /></span><span>{item.suite}</span><span className={`case-priority ${item.priority.toLowerCase()}`}>{item.priority}</span><span className={`case-status ${item.status.toLowerCase().replace(' ', '-')}`}>{item.status}</span><span className="jira-avatar">{item.owner}</span><CaseActionsMenu item={item} onEdit={onEdit} onDelete={onDelete} onAttach={onAttach} /></div> }
function CaseModal({ modal, draft, setDraft, onSave, onClose }) { return <div className="modal-backdrop"><form className="issue-modal" onSubmit={onSave}><button className="modal-close" type="button" onClick={onClose}>×</button><p className="testrail-kicker">Test repository</p><h2>{modal.type === 'create' ? 'Create test case' : 'Update test case'}</h2><label>Title<input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} placeholder="Describe the test scenario" autoFocus required /></label><label>Suite<input value={draft.suite} onChange={(event) => setDraft({ ...draft, suite: event.target.value })} /></label><div className="form-grid"><label>Priority<select value={draft.priority} onChange={(event) => setDraft({ ...draft, priority: event.target.value })}><option>High</option><option>Normal</option><option>Low</option></select></label><label>Status<select value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value })}><option>Not run</option><option>Passed</option><option>Failed</option><option>Blocked</option></select></label></div><label>Test steps<textarea rows="4" placeholder="Add steps and expected results..." /></label><div><button type="button" onClick={onClose}>Cancel</button><button className="testrail-primary" type="submit">Save case</button></div></form></div> }
export default TestCases
