[options]
admin_passwd = elevate-admin-change-me
db_host = db
db_port = 5432
db_user = erp
db_password = erp
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
proxy_mode = True
without_demo = all
