"""initial Elevate platform schema

Revision ID: 20260901_01
Revises:
Create Date: 2026-09-01
"""
from alembic import op
import sqlalchemy as sa

revision = "20260901_01"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Older development builds created this schema with SQLAlchemy create_all().
    # Treat that unversioned database as the baseline instead of trying to recreate it.
    if "users" in sa.inspect(op.get_bind()).get_table_names():
        return
    legacy_workspace = "workspace_data" in sa.inspect(op.get_bind()).get_table_names()
    op.create_table("users", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("email", sa.String(255), nullable=False, unique=True), sa.Column("full_name", sa.String(160), nullable=False), sa.Column("password_hash", sa.String(512), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("organizations", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(160), nullable=False), sa.Column("slug", sa.String(100), nullable=False, unique=True), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("memberships", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("organization_id", sa.Integer(), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("role", sa.String(30), nullable=False, server_default="member"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.UniqueConstraint("user_id", "organization_id", name="uq_membership_user_org"))
    op.create_table("projects", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("organization_id", sa.Integer(), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(180), nullable=False), sa.Column("key", sa.String(12), nullable=False), sa.Column("description", sa.Text(), nullable=False, server_default=""), sa.Column("status", sa.String(30), nullable=False, server_default="active"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.UniqueConstraint("organization_id", "key", name="uq_project_org_key"))
    op.create_table("issues", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("issue_key", sa.String(30), nullable=False, unique=True), sa.Column("title", sa.String(255), nullable=False), sa.Column("description", sa.Text(), nullable=False, server_default=""), sa.Column("issue_type", sa.String(30), nullable=False, server_default="task"), sa.Column("status", sa.String(30), nullable=False, server_default="todo"), sa.Column("priority", sa.String(30), nullable=False, server_default="medium"), sa.Column("assignee_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("reporter_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=False), sa.Column("sprint", sa.String(100)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("test_cases", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("preconditions", sa.Text(), nullable=False, server_default=""), sa.Column("steps", sa.JSON(), nullable=False), sa.Column("expected_result", sa.Text(), nullable=False, server_default=""), sa.Column("priority", sa.String(30), nullable=False, server_default="medium"), sa.Column("linked_issue_id", sa.Integer(), sa.ForeignKey("issues.id", ondelete="SET NULL")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("test_runs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(200), nullable=False), sa.Column("description", sa.Text(), nullable=False, server_default=""), sa.Column("status", sa.String(30), nullable=False, server_default="active"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("test_results", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("test_run_id", sa.Integer(), sa.ForeignKey("test_runs.id", ondelete="CASCADE"), nullable=False), sa.Column("test_case_id", sa.Integer(), sa.ForeignKey("test_cases.id", ondelete="CASCADE"), nullable=False), sa.Column("status", sa.String(30), nullable=False, server_default="untested"), sa.Column("comment", sa.Text(), nullable=False, server_default=""), sa.Column("evidence_url", sa.String(500)), sa.Column("defect_issue_id", sa.Integer(), sa.ForeignKey("issues.id", ondelete="SET NULL")), sa.Column("tested_by_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.UniqueConstraint("test_run_id", "test_case_id", name="uq_result_run_case"))
    op.create_table("approval_requests", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("organization_id", sa.Integer(), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("category", sa.String(80), nullable=False, server_default="general"), sa.Column("amount", sa.Integer()), sa.Column("status", sa.String(30), nullable=False, server_default="pending"), sa.Column("requested_by_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=False), sa.Column("approved_by_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("decision_note", sa.Text(), nullable=False, server_default=""), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("notifications", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("body", sa.Text(), nullable=False, server_default=""), sa.Column("kind", sa.String(40), nullable=False, server_default="system"), sa.Column("is_read", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    if not legacy_workspace:
        op.create_table("workspace_data", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("organization_id", sa.Integer(), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False), sa.Column("key", sa.String(100), nullable=False), sa.Column("value", sa.JSON(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.UniqueConstraint("organization_id", "key", name="uq_workspace_data_org_key"))
    if "audit_events" not in sa.inspect(op.get_bind()).get_table_names():
        op.create_table("audit_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("action", sa.String(100), nullable=False), sa.Column("resource_key", sa.String(100), nullable=False), sa.Column("actor", sa.String(120), nullable=False, server_default="system"), sa.Column("detail", sa.Text(), nullable=False, server_default=""), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))


def downgrade():
    for table in ("audit_events", "workspace_data", "notifications", "approval_requests", "test_results", "test_runs", "test_cases", "issues", "projects", "memberships", "organizations", "users"): op.drop_table(table)
