import { useState } from 'react'
import ThemeToggle from '../../components/ThemeToggle'

const projects = [
  { key: 'RH', name: 'RH98 Brand Platform', type: 'Software project', color: 'purple', progress: 68, issues: 24 },
  { key: 'WEB', name: 'Website Refresh', type: 'Marketing project', color: 'orange', progress: 42, issues: 12 },
  { key: 'APP', name: 'Mobile Experience', type: 'Product project', color: 'green', progress: 18, issues: 8 },
]

function JiraNav() {
  return <aside className="jira-sidebar"><a className="jira-logo" href="/jira"><span>✦</span> RH98 <small>JIRA</small></a><button className="jira-workspace"><span>R</span><b>RH98 Workspace</b><i>⌄</i></button><nav><p>Workspace</p><a href="/workspace">✦ Command center</a><a className="jira-active" href="/jira">▦ Dashboard</a><a href="/jira/board">▥ Scrum board</a><a href="/company/personal/user/1/inbox/">▣ Inbox <b>3</b></a><a href="/company/personal/user/1/tasks/">✓ My tasks</a><p>Projects</p>{projects.map((project) => <a href="/jira/board" key={project.key}><i className={`jira-dot ${project.color}`} />{project.key} · {project.name}</a>)}</nav><div className="jira-sidebar-bottom"><a href="/jira/customize">⚙ Customize</a><a href="/help">? Help center</a><span className="jira-profile"><strong>RH</strong><span>Raja Haroon<small>Admin</small></span></span></div></aside>
}

function JiraDashboard() {
  const [range, setRange] = useState('This week')
  return <main className="jira-app"><JiraNav /><section className="jira-main"><header className="jira-topbar"><div className="jira-breadcrumb">RH98 Workspace <b>/</b> Dashboard</div><div className="jira-actions"><label>⌕ <input placeholder="Search" /></label><ThemeToggle /><a className="app-settings-button" href="/jira/customize" aria-label="Open app settings" title="App settings">⚙</a><button>＋</button><button className="jira-user">RH</button></div></header><div className="jira-dashboard"><div className="jira-welcome"><div><p className="jira-kicker">Good morning, Raja</p><h1>Workspace overview</h1><p>See what your team is working on and what needs your attention.</p></div><a className="jira-primary" href="/jira/projects/new">＋ Create project</a></div><div className="jira-stat-grid"><Stat number="44" label="Open issues" tone="purple" /><Stat number="12" label="In progress" tone="orange" /><Stat number="28" label="Completed this month" tone="green" /><Stat number="3" label="Active sprints" tone="blue" /></div><section className="jira-section"><div className="jira-section-head"><div><h2>Your projects</h2><p>Track progress across every team.</p></div><a href="/jira/projects/new">View all projects →</a></div><div className="project-grid">{projects.map((project) => <article className="project-card" key={project.key}><div className={`project-icon ${project.color}`}>{project.key.slice(0, 1)}</div><span className="project-type">{project.type}</span><h3>{project.name}</h3><div className="progress-line"><span style={{ width: `${project.progress}%` }} /></div><footer><span>{project.progress}% complete</span><b>{project.issues} open issues</b></footer><a href="/jira/board" className="project-open">Open project →</a></article>)}</div></section><section className="jira-section sprint-section"><div className="jira-section-head"><div><h2>Sprint progress</h2><p>RH98 Brand Platform · Sprint 08</p></div><div className="range-toggle">{['This week', 'This month'].map((item) => <button className={range === item ? 'selected' : ''} onClick={() => setRange(item)} key={item}>{item}</button>)}</div></div><div className="sprint-progress"><div className="sprint-ring"><strong>68%</strong><small>complete</small></div><div className="sprint-bars"><Bar label="To do" number="8" width="32" color="purple" /><Bar label="In progress" number="5" width="53" color="orange" /><Bar label="Done" number="16" width="82" color="green" /></div><a href="/jira/board" className="jira-secondary">Open sprint board →</a></div></section></div></section></main>
}

function Stat({ number, label, tone }) { return <div className="jira-stat"><span className={`stat-icon ${tone}`}>▦</span><div><strong>{number}</strong><small>{label}</small></div><i>↗</i></div> }
function Bar({ label, number, width, color }) { return <div className="sprint-bar"><span>{label}</span><b>{number}</b><div><i className={color} style={{ width: `${width}%` }} /></div></div> }
export default JiraDashboard
