{
    "name": "Elevate ERP Core",
    "summary": "Multi-company branches, approvals and audit-ready ERP controls",
    "version": "19.0.1.0.0",
    "category": "Administration",
    "author": "Elevate ERP",
    "license": "LGPL-3",
    "depends": ["base", "mail", "stock"],
    "data": [
        "security/elevate_erp_security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/dashboard_data.xml",
        "views/erp_branch_views.xml",
        "views/erp_department_views.xml",
        "views/approval_policy_views.xml",
        "views/approval_request_views.xml",
        "views/audit_log_views.xml",
        "views/erp_dashboard_views.xml",
        "views/erp_core_menus.xml",
    ],
    "application": True,
    "installable": True,
}
