import { useMemo, useState } from 'react'
import './ErpModule.css'

const content = {
  sales: { title: 'Sales', subtitle: 'Manage orders, customers and your sales pipeline.', action: 'Create order', stats: [['$84,240', 'Revenue this month'], ['1,284', 'Total orders'], ['94.8%', 'Fulfilment rate']], columns: ['ORDER', 'CUSTOMER', 'DATE', 'AMOUNT', 'STATUS'], rows: [['SO-1048', 'Apex Technologies', 'Aug 24, 2026', '$4,800.00', 'Paid'], ['SO-1047', 'Orbit Solutions', 'Aug 24, 2026', '$2,340.00', 'Pending'], ['SO-1046', 'Nova Retail', 'Aug 23, 2026', '$1,280.00', 'Processing'], ['SO-1045', 'Vertex Labs', 'Aug 23, 2026', '$6,720.00', 'Paid']] },
  inventory: { title: 'Inventory', subtitle: 'Keep stock levels, products and suppliers under control.', action: 'Add product', stats: [['2,486', 'Items in stock'], ['24', 'Low-stock products'], ['$126,540', 'Inventory value']], columns: ['SKU', 'PRODUCT', 'CATEGORY', 'IN STOCK', 'STATUS'], rows: [['PRD-0091', 'Wireless keyboard', 'Accessories', '124 units', 'In stock'], ['PRD-0142', '27” 4K Monitor', 'Displays', '8 units', 'Low stock'], ['PRD-0186', 'USB-C Dock', 'Accessories', '56 units', 'In stock'], ['PRD-0224', 'Ergonomic chair', 'Furniture', '4 units', 'Low stock']] },
  finance: { title: 'Finance', subtitle: 'Track invoices, expenses and your business cash flow.', action: 'Create invoice', stats: [['$12,560', 'Outstanding invoices'], ['$68,920', 'Paid this month'], ['$21,340', 'Monthly expenses']], columns: ['INVOICE', 'CUSTOMER', 'DUE DATE', 'AMOUNT', 'STATUS'], rows: [['INV-2048', 'Apex Technologies', 'Aug 28, 2026', '$4,800.00', 'Paid'], ['INV-2047', 'Orbit Solutions', 'Aug 26, 2026', '$2,340.00', 'Overdue'], ['INV-2046', 'Nova Retail', 'Sep 01, 2026', '$1,280.00', 'Sent'], ['INV-2045', 'Vertex Labs', 'Aug 30, 2026', '$6,720.00', 'Paid']] },
  hr: { title: 'Human resources', subtitle: 'Bring your people, leave and attendance into one place.', action: 'Add employee', stats: [['48', 'Active employees'], ['3', 'Pending leave requests'], ['96%', 'Attendance this month']], columns: ['EMPLOYEE', 'DEPARTMENT', 'ROLE', 'STATUS', 'JOINED'], rows: [['Ayesha Khan', 'Design', 'Product designer', 'Active', 'Jan 15, 2025'], ['Hamza Ali', 'Engineering', 'Frontend developer', 'Active', 'Mar 02, 2025'], ['Sara Ahmed', 'Operations', 'Operations manager', 'On leave', 'Nov 19, 2024'], ['Usman Tariq', 'Sales', 'Account executive', 'Active', 'Jul 08, 2025']] },
}

function ErpModule({ type }) {
  const data = content[type] || content.sales
  const [query, setQuery] = useState('')
  const [rows, setRows] = useState(data.rows)
  const [message, setMessage] = useState('')
  const filtered = useMemo(() => rows.filter(row => row.join(' ').toLowerCase().includes(query.toLowerCase())), [rows, query])
  function addRecord() { const item = type === 'hr' ? ['New employee', 'Unassigned', 'Team member', 'Active', 'Today'] : type === 'inventory' ? ['PRD-NEW', 'New product', 'Uncategorized', '0 units', 'Low stock'] : type === 'finance' ? ['INV-NEW', 'New customer', 'Sep 05, 2026', '$0.00', 'Draft'] : ['SO-NEW', 'New customer', 'Today', '$0.00', 'Draft']; setRows([item, ...rows]); setMessage('New draft record has been added.') }
  return <main className="erp-module-page"><aside className="erp-module-sidebar"><a href="/erp" className="erp-module-brand"><span>e</span>Elevate <small>ERP</small></a><nav><a href="/erp">▦ Overview</a><a className={type === 'sales' ? 'active' : ''} href="/erp/sales">▣ Sales</a><a className={type === 'inventory' ? 'active' : ''} href="/erp/inventory">▤ Inventory</a><a className={type === 'finance' ? 'active' : ''} href="/erp/finance">◉ Finance</a><a className={type === 'hr' ? 'active' : ''} href="/erp/hr">♙ Human resources</a><a href="/settings">⚙ Settings</a></nav><div className="erp-module-user"><b>RH</b><span>Raja Haroon<small>Administrator</small></span></div></aside><section className="erp-module-main"><header className="erp-module-top"><a href="/erp">← Dashboard</a><div><button>♢</button><b>RH</b></div></header><div className="erp-module-content"><div className="module-title"><div><p>ERP / {data.title}</p><h1>{data.title}</h1><small>{data.subtitle}</small></div><button onClick={addRecord}>＋ {data.action}</button></div>{message && <div className="module-message">{message}<button onClick={() => setMessage('')}>×</button></div>}<section className="module-stats">{data.stats.map(([value,label]) => <article key={label}><span>◈</span><strong>{value}</strong><small>{label}</small></article>)}</section><section className="module-panel"><header><div><h2>{type === 'hr' ? 'Employees' : type === 'inventory' ? 'Products' : type === 'finance' ? 'Invoices' : 'Sales orders'}</h2><p>All records in one place</p></div><div className="module-tools"><label>⌕ <input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search records" /></label><button>Filter</button></div></header><div className="module-table"><div className="module-row module-row-head">{data.columns.map(col => <span key={col}>{col}</span>)}</div>{filtered.length ? filtered.map((row,index) => <div className="module-row" key={`${row[0]}-${index}`}>{row.map((cell,index) => index === 0 ? <b key={cell}>{cell}</b> : index === 4 ? <i key={cell} className={cell.toLowerCase().replace(' ','-')}>{cell}</i> : <span key={cell}>{cell}</span>)}</div>) : <p className="module-empty">No matching records found.</p>}</div></section></div></section></main>
}

export default ErpModule
